# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"background": "00_GenerateSyntheticImages.ipynb",
         "radial_grid": "00_GenerateSyntheticImages.ipynb",
         "particle_bessel_response": "00_GenerateSyntheticImages.ipynb",
         "add_noise": "00_GenerateSyntheticImages.ipynb",
         "generate_particles": "00_GenerateSyntheticImages.ipynb",
         "define_image": "00_GenerateSyntheticImages.ipynb",
         "generate_image": "00_GenerateSyntheticImages.ipynb",
         "add_target": "00_GenerateSyntheticImages.ipynb",
         "generate_mask": "00_GenerateSyntheticImages.ipynb",
         "annotate_image": "00_GenerateSyntheticImages.ipynb",
         "save_img": "00_GenerateSyntheticImages.ipynb",
         "generate_images": "00_GenerateSyntheticImages.ipynb",
         "Flatten": "01_models.ipynb",
         "DeepTrackNet": "01_models.ipynb",
         "track_frame": "02_Video.ipynb",
         "track": "02_Video.ipynb",
         "plot_tracked_scanning_boxes": "02_Video.ipynb",
         "centroids": "02_Video.ipynb",
         "show_tracked_frames": "02_Video.ipynb",
         "track_single_particle": "02_Video.ipynb",
         "show_tracked_frames_single_particle": "02_Video.ipynb",
         "particle_positions": "02_Video.ipynb",
         "lsradialcenterfit": "03_Measures.ipynb",
         "radialcenter": "03_Measures.ipynb",
         "MAELossFlat": "04_fastai_adpater.ipynb",
         "npimg2tensor": "04_fastai_adpater.ipynb",
         "MImageList": "04_fastai_adpater.ipynb",
         "CustomSegmentationLabelList": "04_fastai_adpater.ipynb",
         "CustomSegmentationItemList": "04_fastai_adpater.ipynb",
         "XYRItem": "04_fastai_adpater.ipynb",
         "XYRList": "04_fastai_adpater.ipynb",
         "show_arr": "98_Display.ipynb",
         "format_bessel_example": "98_Display.ipynb",
         "show_images_dir": "98_Display.ipynb",
         "dtt_extract": "99_cli.ipynb"}

modules = ["simg.py",
           "models.py",
           "video.py",
           "measures.py",
           "fastai_adapter.py",
           "disp.py",
           "cli.py"]

doc_url = "https://wooduk.github.io/deeptracktorch/"

git_url = "https://github.com/wooduk/deeptracktorch/tree/master/"

def custom_doc_links(name): return None
