# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/98_Display.ipynb (unless otherwise specified).

__all__ = ['format_bessel_example']

# Cell
import altair as alt
import pandas as pd

# Cell
def format_bessel_example(a):
    # legend, axes labels and markers
    a.axhline(0,c='grey',linestyle='--',lw=1)
    #suffix=['th','st','nd','rd','th']
    #a.legend([f"${o}^{{{suffix[np.clip(o,0,4)]}}}$" for o in bessel_order])
    a.set_xlabel('$r$');
    a.set_ylabel('$f(order,r)$')
    a.minorticks_on(); a.grid(True,which='minor',c='#eeeeee');
    a.grid(True,which='major',c='#aaaaaa')
    a.set_title("Response of `scipy.special.jv()` for values of $order$ and $r$", fontsize=16)
    a.set_ylim([-0.5,1.0]);
    a.set_xlim([0,50]);